import { useState } from "react";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { Sparkles, Send, Loader2 } from "lucide-react";
import { useFaults } from "@/hooks/useFaults";
import { useFacilities } from "@/hooks/useFacilities";
import { useWorkers } from "@/hooks/useWorkers";
import { useAuth } from "@/contexts/AuthContext";

interface AIReportDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export const AIReportDialog = ({ open, onOpenChange }: AIReportDialogProps) => {
  const [recipientEmail, setRecipientEmail] = useState("");
  const [additionalNotes, setAdditionalNotes] = useState("");
  const [isSending, setIsSending] = useState(false);
  const { toast } = useToast();
  const { user } = useAuth();
  
  const { data: faults } = useFaults();
  const { data: facilities } = useFacilities();
  const { data: workers } = useWorkers();

  const generateReportSummary = () => {
    const openFaults = faults?.filter(f => f.status === 'open').length || 0;
    const inProgressFaults = faults?.filter(f => f.status === 'in-progress').length || 0;
    const resolvedFaults = faults?.filter(f => f.status === 'resolved').length || 0;
    const totalFacilities = facilities?.length || 0;
    const avgHealth = facilities?.reduce((sum, f) => sum + f.health_percentage, 0) / (totalFacilities || 1);
    const presentWorkers = workers?.filter(w => w.is_present).length || 0;
    const totalWorkers = workers?.length || 0;

    return `
📊 Facility Management Report

🏢 Facilities Overview:
- Total Facilities: ${totalFacilities}
- Average Health: ${avgHealth.toFixed(1)}%

🔧 Faults Status:
- Open: ${openFaults}
- In Progress: ${inProgressFaults}
- Resolved: ${resolvedFaults}

👷 Workers:
- Present: ${presentWorkers}/${totalWorkers}

${additionalNotes ? `📝 Additional Notes:\n${additionalNotes}` : ''}

Generated by FacilityHub AI
    `.trim();
  };

  const handleSendReport = async () => {
    if (!recipientEmail) {
      toast({
        title: "Email required",
        description: "Please enter a recipient email address",
        variant: "destructive",
      });
      return;
    }

    setIsSending(true);
    
    // Simulate sending (in production, this would call an edge function)
    try {
      await new Promise(resolve => setTimeout(resolve, 1500));
      
      toast({
        title: "Report sent!",
        description: `AI report has been sent to ${recipientEmail}`,
      });
      
      setRecipientEmail("");
      setAdditionalNotes("");
      onOpenChange(false);
    } catch (error) {
      toast({
        title: "Failed to send",
        description: "Could not send the AI report. Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsSending(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Sparkles className="h-5 w-5 text-primary" />
            Send AI Report
          </DialogTitle>
          <DialogDescription>
            Generate and send an AI-powered summary of your facility status
          </DialogDescription>
        </DialogHeader>
        
        <div className="space-y-4 pt-4">
          <div className="space-y-2">
            <Label htmlFor="email">Recipient Email</Label>
            <Input
              id="email"
              type="email"
              placeholder="recipient@example.com"
              value={recipientEmail}
              onChange={(e) => setRecipientEmail(e.target.value)}
            />
          </div>
          
          <div className="space-y-2">
            <Label htmlFor="notes">Additional Notes (Optional)</Label>
            <Textarea
              id="notes"
              placeholder="Add any additional context or notes..."
              value={additionalNotes}
              onChange={(e) => setAdditionalNotes(e.target.value)}
              rows={3}
            />
          </div>
          
          <div className="rounded-lg bg-muted p-4">
            <h4 className="text-sm font-medium mb-2">Report Preview</h4>
            <pre className="text-xs text-muted-foreground whitespace-pre-wrap font-mono">
              {generateReportSummary()}
            </pre>
          </div>
          
          <Button 
            onClick={handleSendReport} 
            className="w-full" 
            disabled={isSending}
          >
            {isSending ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Sending...
              </>
            ) : (
              <>
                <Send className="mr-2 h-4 w-4" />
                Send Report
              </>
            )}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
};