// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qbqqmzcgggzrdehbuiew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFicXFtemNnZ2d6cmRlaGJ1aWV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgyNDM3MTYsImV4cCI6MjA4MzgxOTcxNn0.uJFW-1U7QF0Wii_Ze1Y843fI0FKZqFhTYbfBBNbRKI8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});